### PR TITLE
Add DAO Active and Inactive Proposal  

### LINKED ISSUE #71: add DAO proposals archive
remove voting buttons on proposals whose voting period has expired and place them in a searchable archive to facilitate user voting and viewing expired proposals

### PR DESCRIPTION
**Pull request by amiraabouhadid**
separate active proposals from inactive proposals so it is easier for the user to navigate and vote on proposals

### CODE REVIEW

**Comment by DylanVerstraete** [comment]
Inactive proposals (proposals that are closed) are removed from storage. So no historical proposals can be searched

**Comment by amiraabouhadid** [comment]
> Inactive proposals (proposals that are closed) are removed from storage. So no historical proposals can be searched

@DylanVerstraete That is strange because I can retrieve proposals that voting has closed on :
Screenshot from 2022-07-05 13-03-06
Screenshot from 2022-07-05 13-03-14
Screenshot from 2022-07-05 13-03-23

**Comment by DylanVerstraete** [comment]
@amiraabouhadid yes proposals can still be read if they are not closed. When a proposal expires it is not closed automatically. It's okay to read proposals that are "finished" but they will dissapear when they are "closed". Closing a proposal perform the underlying action (needs to be done manually)

**Comment by amiraabouhadid** [comment]
@DylanVerstraete so is it just the naming "archived" that is confusing?

**Comment by DylanVerstraete** [comment]
> @DylanVerstraete so is it just the naming "archived" that is confusing?

Yeah, I would call it "finished" 

Maybe with a node: not executed yet

**Review by MohamedElmdary — APPROVED** [review]

**Pull request merged**
